// tse_core.v

// This file was auto-generated from altera_eth_tse_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 22.1 922

`timescale 1 ps / 1 ps
module tse_core (
		input  wire         clk,                //        control_port_clock_connection.clk
		input  wire         reset,              //                     reset_connection.reset
		output wire [31:0]  reg_data_out,       //                         control_port.readdata
		input  wire         reg_rd,             //                                     .read
		input  wire [31:0]  reg_data_in,        //                                     .writedata
		input  wire         reg_wr,             //                                     .write
		output wire         reg_busy,           //                                     .waitrequest
		input  wire [7:0]   reg_addr,           //                                     .address
		input  wire         rx_afull_clk,       // receive_fifo_status_clock_connection.clk
		input  wire [1:0]   rx_afull_data,      //                  receive_fifo_status.data
		input  wire         rx_afull_valid,     //                                     .valid
		input  wire [0:0]   rx_afull_channel,   //                                     .channel
		output wire         mac_rx_clk_0,       //            mac_rx_clock_connection_0.clk
		output wire         mac_tx_clk_0,       //            mac_tx_clock_connection_0.clk
		output wire [7:0]   data_rx_data_0,     //                            receive_0.data
		output wire         data_rx_eop_0,      //                                     .endofpacket
		output wire [4:0]   data_rx_error_0,    //                                     .error
		input  wire         data_rx_ready_0,    //                                     .ready
		output wire         data_rx_sop_0,      //                                     .startofpacket
		output wire         data_rx_valid_0,    //                                     .valid
		input  wire [7:0]   data_tx_data_0,     //                           transmit_0.data
		input  wire         data_tx_eop_0,      //                                     .endofpacket
		input  wire         data_tx_error_0,    //                                     .error
		output wire         data_tx_ready_0,    //                                     .ready
		input  wire         data_tx_sop_0,      //                                     .startofpacket
		input  wire         data_tx_valid_0,    //                                     .valid
		output wire [4:0]   pkt_class_data_0,   //                receive_packet_type_0.data
		output wire         pkt_class_valid_0,  //                                     .valid
		input  wire         tx_crc_fwd_0,       //                mac_misc_connection_0.export
		input  wire         ref_clk,            //         pcs_ref_clk_clock_connection.clk
		output wire         led_crs_0,          //              status_led_connection_0.crs
		output wire         led_link_0,         //                                     .link
		output wire         led_panel_link_0,   //                                     .panel_link
		output wire         led_col_0,          //                                     .col
		output wire         led_an_0,           //                                     .an
		output wire         led_char_err_0,     //                                     .char_err
		output wire         led_disp_err_0,     //                                     .disp_err
		output wire         rx_recovclkout_0,   //          serdes_control_connection_0.rx_recovclkout
		input  wire [139:0] reconfig_togxb_0,   //                                     .reconfig_togxb
		output wire [91:0]  reconfig_fromgxb_0, //                                     .reconfig_fromgxb
		input  wire         rxp_0,              //                  serial_connection_0.rxp
		output wire         txp_0               //                                     .txp
	);

	wire   [31:0] avalon_arbiter_av_mac_master_0_readdata;                // i_tse_fifoless_mac_0:reg_data_out -> avalon_arbiter:mac_readdata_0
	wire          avalon_arbiter_av_mac_master_0_waitrequest;             // i_tse_fifoless_mac_0:reg_busy -> avalon_arbiter:mac_waitrequest_0
	wire    [7:0] avalon_arbiter_av_mac_master_0_address;                 // avalon_arbiter:mac_address_0 -> i_tse_fifoless_mac_0:reg_addr
	wire          avalon_arbiter_av_mac_master_0_read;                    // avalon_arbiter:mac_read_0 -> i_tse_fifoless_mac_0:reg_rd
	wire   [31:0] avalon_arbiter_av_mac_master_0_writedata;               // avalon_arbiter:mac_writedata_0 -> i_tse_fifoless_mac_0:reg_data_in
	wire          avalon_arbiter_av_mac_master_0_write;                   // avalon_arbiter:mac_write_0 -> i_tse_fifoless_mac_0:reg_wr
	wire          channel_adapter_channel_out_0_valid;                    // channel_adapter:rx_afull_valid_out_0 -> i_tse_fifoless_mac_0:rx_afull_valid
	wire    [1:0] channel_adapter_channel_out_0_data;                     // channel_adapter:rx_afull_data_out_0 -> i_tse_fifoless_mac_0:rx_afull_data
	wire          i_tse_pcs_0_sd_loopback_export;                         // i_tse_pcs_0:sd_loopback -> i_phyip_terminator_0:sd_loopback
	wire    [0:0] i_custom_phyip_0_rx_clkout_export;                      // i_custom_phyip_0:rx_clkout -> i_tse_pcs_0:rx_pcs_clk
	wire    [0:0] i_custom_phyip_0_rx_disperr_export;                     // i_custom_phyip_0:rx_disperr -> i_tse_pcs_0:rx_disp_err
	wire    [0:0] i_custom_phyip_0_tx_clkout_export;                      // i_custom_phyip_0:tx_clkout -> i_tse_pcs_0:tx_pcs_clk
	wire    [0:0] i_custom_phyip_0_rx_runningdisp_export;                 // i_custom_phyip_0:rx_runningdisp -> i_tse_pcs_0:rx_runningdisp
	wire    [7:0] i_custom_phyip_0_rx_parallel_data_export;               // i_custom_phyip_0:rx_parallel_data -> i_tse_pcs_0:rx_frame
	wire    [0:0] i_custom_phyip_0_rx_rlv_export;                         // i_custom_phyip_0:rx_rlv -> i_tse_pcs_0:rx_runlengthviolation
	wire    [0:0] i_custom_phyip_0_rx_errdetect_export;                   // i_custom_phyip_0:rx_errdetect -> i_tse_pcs_0:rx_char_err_gx
	wire    [7:0] i_tse_pcs_0_tx_frame_export;                            // i_tse_pcs_0:tx_frame -> i_custom_phyip_0:tx_parallel_data
	wire    [0:0] i_custom_phyip_0_rx_patterndetect_export;               // i_custom_phyip_0:rx_patterndetect -> i_tse_pcs_0:rx_patterndetect
	wire    [0:0] i_custom_phyip_0_rx_datak_export;                       // i_custom_phyip_0:rx_datak -> i_tse_pcs_0:rx_kchar
	wire    [0:0] i_custom_phyip_0_rx_syncstatus_export;                  // i_custom_phyip_0:rx_syncstatus -> i_tse_pcs_0:rx_syncstatus
	wire    [4:0] i_custom_phyip_0_rx_bitslipboundaryselectout_export;    // i_custom_phyip_0:rx_bitslipboundaryselectout -> i_tse_pcs_0:wa_boundary
	wire          i_tse_pcs_0_tx_kchar_export;                            // i_tse_pcs_0:tx_kchar -> i_custom_phyip_0:tx_datak
	wire    [0:0] i_custom_phyip_0_rx_rmfifodatainserted_export;          // i_custom_phyip_0:rx_rmfifodatainserted -> i_tse_pcs_0:rx_rmfifodatainserted
	wire    [0:0] i_custom_phyip_0_rx_rmfifodatadeleted_export;           // i_custom_phyip_0:rx_rmfifodatadeleted -> i_tse_pcs_0:rx_rmfifodatadeleted
	wire          i_custom_phyip_0_tx_ready_export;                       // i_custom_phyip_0:tx_ready -> i_phyip_terminator_0:tx_ready
	wire    [0:0] i_custom_phyip_0_tx_serial_data_export;                 // i_custom_phyip_0:tx_serial_data -> i_phyip_terminator_0:tx_serial_data
	wire  [139:0] i_phyip_terminator_0_reconfig_to_xcvr_reconfig_to_xcvr; // i_phyip_terminator_0:reconfig_to_xcvr -> i_custom_phyip_0:reconfig_to_xcvr
	wire    [0:0] i_custom_phyip_0_pll_locked_export;                     // i_custom_phyip_0:pll_locked -> i_phyip_terminator_0:pll_locked
	wire   [91:0] i_custom_phyip_0_reconfig_from_xcvr_reconfig_from_xcvr; // i_custom_phyip_0:reconfig_from_xcvr -> i_phyip_terminator_0:reconfig_from_xcvr
	wire          i_custom_phyip_0_rx_ready_export;                       // i_custom_phyip_0:rx_ready -> i_phyip_terminator_0:rx_ready
	wire          i_phyip_terminator_0_rx_serial_data_export;             // i_phyip_terminator_0:rx_serial_data -> i_custom_phyip_0:rx_serial_data
	wire    [0:0] i_custom_phyip_0_rx_recovered_clk_export;               // i_custom_phyip_0:rx_recovered_clk -> i_phyip_terminator_0:rx_recovered_clk
	wire   [31:0] i_phyip_terminator_0_av_dummy_master_readdata;          // i_custom_phyip_0:phy_mgmt_readdata -> i_phyip_terminator_0:readdata
	wire          i_phyip_terminator_0_av_dummy_master_waitrequest;       // i_custom_phyip_0:phy_mgmt_waitrequest -> i_phyip_terminator_0:waitrequest
	wire    [8:0] i_phyip_terminator_0_av_dummy_master_address;           // i_phyip_terminator_0:address -> i_custom_phyip_0:phy_mgmt_address
	wire          i_phyip_terminator_0_av_dummy_master_read;              // i_phyip_terminator_0:read -> i_custom_phyip_0:phy_mgmt_read
	wire   [31:0] i_phyip_terminator_0_av_dummy_master_writedata;         // i_phyip_terminator_0:writedata -> i_custom_phyip_0:phy_mgmt_writedata
	wire          i_phyip_terminator_0_av_dummy_master_write;             // i_phyip_terminator_0:write -> i_custom_phyip_0:phy_mgmt_write
	wire   [15:0] avalon_arbiter_av_pcs_master_0_readdata;                // i_tse_pcs_0:reg_data_out -> avalon_arbiter:pcs_readdata_0
	wire          avalon_arbiter_av_pcs_master_0_waitrequest;             // i_tse_pcs_0:reg_busy -> avalon_arbiter:pcs_waitrequest_0
	wire    [4:0] avalon_arbiter_av_pcs_master_0_address;                 // avalon_arbiter:pcs_address_0 -> i_tse_pcs_0:reg_addr
	wire          avalon_arbiter_av_pcs_master_0_read;                    // avalon_arbiter:pcs_read_0 -> i_tse_pcs_0:reg_rd
	wire   [15:0] avalon_arbiter_av_pcs_master_0_writedata;               // avalon_arbiter:pcs_writedata_0 -> i_tse_pcs_0:reg_data_in
	wire          avalon_arbiter_av_pcs_master_0_write;                   // avalon_arbiter:pcs_write_0 -> i_tse_pcs_0:reg_wr
	wire          i_tse_pcs_0_pcs_transmit_clock_connection_clk;          // i_tse_pcs_0:tx_clk -> [i_tse_fifoless_mac_0:tx_clk, rst_controller_001:clk]
	wire          i_tse_pcs_0_pcs_receive_clock_connection_clk;           // i_tse_pcs_0:rx_clk -> [i_tse_fifoless_mac_0:rx_clk, rst_controller_002:clk]
	wire    [7:0] i_tse_pcs_0_gmii_connection_gmii_rx_d;                  // i_tse_pcs_0:gmii_rx_d -> i_tse_fifoless_mac_0:gm_rx_d
	wire          i_tse_pcs_0_gmii_connection_gmii_rx_err;                // i_tse_pcs_0:gmii_rx_err -> i_tse_fifoless_mac_0:gm_rx_err
	wire          i_tse_pcs_0_gmii_connection_gmii_rx_dv;                 // i_tse_pcs_0:gmii_rx_dv -> i_tse_fifoless_mac_0:gm_rx_dv
	wire    [7:0] i_tse_fifoless_mac_0_mac_gmii_connection_gmii_tx_d;     // i_tse_fifoless_mac_0:gm_tx_d -> i_tse_pcs_0:gmii_tx_d
	wire          i_tse_fifoless_mac_0_mac_gmii_connection_gmii_tx_en;    // i_tse_fifoless_mac_0:gm_tx_en -> i_tse_pcs_0:gmii_tx_en
	wire          i_tse_fifoless_mac_0_mac_gmii_connection_gmii_tx_err;   // i_tse_fifoless_mac_0:gm_tx_err -> i_tse_pcs_0:gmii_tx_err
	wire          i_tse_fifoless_mac_0_mac_mii_connection_mii_tx_en;      // i_tse_fifoless_mac_0:m_tx_en -> i_tse_pcs_0:mii_tx_en
	wire    [3:0] i_tse_pcs_0_mii_connection_mii_rx_d;                    // i_tse_pcs_0:mii_rx_d -> i_tse_fifoless_mac_0:m_rx_d
	wire          i_tse_pcs_0_mii_connection_mii_col;                     // i_tse_pcs_0:mii_col -> i_tse_fifoless_mac_0:m_rx_col
	wire    [3:0] i_tse_fifoless_mac_0_mac_mii_connection_mii_tx_d;       // i_tse_fifoless_mac_0:m_tx_d -> i_tse_pcs_0:mii_tx_d
	wire          i_tse_fifoless_mac_0_mac_mii_connection_mii_tx_err;     // i_tse_fifoless_mac_0:m_tx_err -> i_tse_pcs_0:mii_tx_err
	wire          i_tse_pcs_0_mii_connection_mii_crs;                     // i_tse_pcs_0:mii_crs -> i_tse_fifoless_mac_0:m_rx_crs
	wire          i_tse_pcs_0_mii_connection_mii_rx_err;                  // i_tse_pcs_0:mii_rx_err -> i_tse_fifoless_mac_0:m_rx_err
	wire          i_tse_pcs_0_mii_connection_mii_rx_dv;                   // i_tse_pcs_0:mii_rx_dv -> i_tse_fifoless_mac_0:m_rx_en
	wire          i_tse_pcs_0_sgmii_status_connection_set_1000;           // i_tse_pcs_0:set_1000 -> i_tse_fifoless_mac_0:set_1000
	wire          i_tse_pcs_0_sgmii_status_connection_set_10;             // i_tse_pcs_0:set_10 -> i_tse_fifoless_mac_0:set_10
	wire          i_tse_pcs_0_clock_enable_connection_tx_clkena;          // i_tse_pcs_0:tx_clkena -> i_tse_fifoless_mac_0:tx_clkena
	wire          i_tse_pcs_0_clock_enable_connection_rx_clkena;          // i_tse_pcs_0:rx_clkena -> i_tse_fifoless_mac_0:rx_clkena
	wire          rst_controller_reset_out_reset;                         // rst_controller:reset_out -> channel_adapter:reset
	wire          rst_controller_001_reset_out_reset;                     // rst_controller_001:reset_out -> i_tse_pcs_0:reset_tx_clk
	wire          rst_controller_002_reset_out_reset;                     // rst_controller_002:reset_out -> i_tse_pcs_0:reset_rx_clk

	altera_eth_tse_avalon_arbiter #(
		.MAX_CHANNELS     (1),
		.MAC_ONLY         (0),
		.SLAVE_ADDR_WIDTH (8)
	) avalon_arbiter (
		.clk                (clk),                                        //             clk.clk
		.reset              (reset),                                      //           reset.reset
		.reg_data_out       (reg_data_out),                               //        av_slave.readdata
		.reg_rd             (reg_rd),                                     //                .read
		.reg_data_in        (reg_data_in),                                //                .writedata
		.reg_wr             (reg_wr),                                     //                .write
		.reg_busy           (reg_busy),                                   //                .waitrequest
		.reg_addr           (reg_addr),                                   //                .address
		.mac_address_0      (avalon_arbiter_av_mac_master_0_address),     // av_mac_master_0.address
		.mac_readdata_0     (avalon_arbiter_av_mac_master_0_readdata),    //                .readdata
		.mac_read_0         (avalon_arbiter_av_mac_master_0_read),        //                .read
		.mac_writedata_0    (avalon_arbiter_av_mac_master_0_writedata),   //                .writedata
		.mac_write_0        (avalon_arbiter_av_mac_master_0_write),       //                .write
		.mac_waitrequest_0  (avalon_arbiter_av_mac_master_0_waitrequest), //                .waitrequest
		.pcs_address_0      (avalon_arbiter_av_pcs_master_0_address),     // av_pcs_master_0.address
		.pcs_readdata_0     (avalon_arbiter_av_pcs_master_0_readdata),    //                .readdata
		.pcs_read_0         (avalon_arbiter_av_pcs_master_0_read),        //                .read
		.pcs_writedata_0    (avalon_arbiter_av_pcs_master_0_writedata),   //                .writedata
		.pcs_write_0        (avalon_arbiter_av_pcs_master_0_write),       //                .write
		.pcs_waitrequest_0  (avalon_arbiter_av_pcs_master_0_waitrequest), //                .waitrequest
		.mac_address_1      (),                                           //     (terminated)
		.mac_readdata_1     (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_1         (),                                           //     (terminated)
		.mac_writedata_1    (),                                           //     (terminated)
		.mac_write_1        (),                                           //     (terminated)
		.mac_waitrequest_1  (1'b0),                                       //     (terminated)
		.pcs_address_1      (),                                           //     (terminated)
		.pcs_readdata_1     (16'b0000000000000000),                       //     (terminated)
		.pcs_read_1         (),                                           //     (terminated)
		.pcs_writedata_1    (),                                           //     (terminated)
		.pcs_write_1        (),                                           //     (terminated)
		.pcs_waitrequest_1  (1'b0),                                       //     (terminated)
		.mac_address_2      (),                                           //     (terminated)
		.mac_readdata_2     (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_2         (),                                           //     (terminated)
		.mac_writedata_2    (),                                           //     (terminated)
		.mac_write_2        (),                                           //     (terminated)
		.mac_waitrequest_2  (1'b0),                                       //     (terminated)
		.pcs_address_2      (),                                           //     (terminated)
		.pcs_readdata_2     (16'b0000000000000000),                       //     (terminated)
		.pcs_read_2         (),                                           //     (terminated)
		.pcs_writedata_2    (),                                           //     (terminated)
		.pcs_write_2        (),                                           //     (terminated)
		.pcs_waitrequest_2  (1'b0),                                       //     (terminated)
		.mac_address_3      (),                                           //     (terminated)
		.mac_readdata_3     (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_3         (),                                           //     (terminated)
		.mac_writedata_3    (),                                           //     (terminated)
		.mac_write_3        (),                                           //     (terminated)
		.mac_waitrequest_3  (1'b0),                                       //     (terminated)
		.pcs_address_3      (),                                           //     (terminated)
		.pcs_readdata_3     (16'b0000000000000000),                       //     (terminated)
		.pcs_read_3         (),                                           //     (terminated)
		.pcs_writedata_3    (),                                           //     (terminated)
		.pcs_write_3        (),                                           //     (terminated)
		.pcs_waitrequest_3  (1'b0),                                       //     (terminated)
		.mac_address_4      (),                                           //     (terminated)
		.mac_readdata_4     (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_4         (),                                           //     (terminated)
		.mac_writedata_4    (),                                           //     (terminated)
		.mac_write_4        (),                                           //     (terminated)
		.mac_waitrequest_4  (1'b0),                                       //     (terminated)
		.pcs_address_4      (),                                           //     (terminated)
		.pcs_readdata_4     (16'b0000000000000000),                       //     (terminated)
		.pcs_read_4         (),                                           //     (terminated)
		.pcs_writedata_4    (),                                           //     (terminated)
		.pcs_write_4        (),                                           //     (terminated)
		.pcs_waitrequest_4  (1'b0),                                       //     (terminated)
		.mac_address_5      (),                                           //     (terminated)
		.mac_readdata_5     (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_5         (),                                           //     (terminated)
		.mac_writedata_5    (),                                           //     (terminated)
		.mac_write_5        (),                                           //     (terminated)
		.mac_waitrequest_5  (1'b0),                                       //     (terminated)
		.pcs_address_5      (),                                           //     (terminated)
		.pcs_readdata_5     (16'b0000000000000000),                       //     (terminated)
		.pcs_read_5         (),                                           //     (terminated)
		.pcs_writedata_5    (),                                           //     (terminated)
		.pcs_write_5        (),                                           //     (terminated)
		.pcs_waitrequest_5  (1'b0),                                       //     (terminated)
		.mac_address_6      (),                                           //     (terminated)
		.mac_readdata_6     (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_6         (),                                           //     (terminated)
		.mac_writedata_6    (),                                           //     (terminated)
		.mac_write_6        (),                                           //     (terminated)
		.mac_waitrequest_6  (1'b0),                                       //     (terminated)
		.pcs_address_6      (),                                           //     (terminated)
		.pcs_readdata_6     (16'b0000000000000000),                       //     (terminated)
		.pcs_read_6         (),                                           //     (terminated)
		.pcs_writedata_6    (),                                           //     (terminated)
		.pcs_write_6        (),                                           //     (terminated)
		.pcs_waitrequest_6  (1'b0),                                       //     (terminated)
		.mac_address_7      (),                                           //     (terminated)
		.mac_readdata_7     (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_7         (),                                           //     (terminated)
		.mac_writedata_7    (),                                           //     (terminated)
		.mac_write_7        (),                                           //     (terminated)
		.mac_waitrequest_7  (1'b0),                                       //     (terminated)
		.pcs_address_7      (),                                           //     (terminated)
		.pcs_readdata_7     (16'b0000000000000000),                       //     (terminated)
		.pcs_read_7         (),                                           //     (terminated)
		.pcs_writedata_7    (),                                           //     (terminated)
		.pcs_write_7        (),                                           //     (terminated)
		.pcs_waitrequest_7  (1'b0),                                       //     (terminated)
		.mac_address_8      (),                                           //     (terminated)
		.mac_readdata_8     (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_8         (),                                           //     (terminated)
		.mac_writedata_8    (),                                           //     (terminated)
		.mac_write_8        (),                                           //     (terminated)
		.mac_waitrequest_8  (1'b0),                                       //     (terminated)
		.pcs_address_8      (),                                           //     (terminated)
		.pcs_readdata_8     (16'b0000000000000000),                       //     (terminated)
		.pcs_read_8         (),                                           //     (terminated)
		.pcs_writedata_8    (),                                           //     (terminated)
		.pcs_write_8        (),                                           //     (terminated)
		.pcs_waitrequest_8  (1'b0),                                       //     (terminated)
		.mac_address_9      (),                                           //     (terminated)
		.mac_readdata_9     (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_9         (),                                           //     (terminated)
		.mac_writedata_9    (),                                           //     (terminated)
		.mac_write_9        (),                                           //     (terminated)
		.mac_waitrequest_9  (1'b0),                                       //     (terminated)
		.pcs_address_9      (),                                           //     (terminated)
		.pcs_readdata_9     (16'b0000000000000000),                       //     (terminated)
		.pcs_read_9         (),                                           //     (terminated)
		.pcs_writedata_9    (),                                           //     (terminated)
		.pcs_write_9        (),                                           //     (terminated)
		.pcs_waitrequest_9  (1'b0),                                       //     (terminated)
		.mac_address_10     (),                                           //     (terminated)
		.mac_readdata_10    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_10        (),                                           //     (terminated)
		.mac_writedata_10   (),                                           //     (terminated)
		.mac_write_10       (),                                           //     (terminated)
		.mac_waitrequest_10 (1'b0),                                       //     (terminated)
		.pcs_address_10     (),                                           //     (terminated)
		.pcs_readdata_10    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_10        (),                                           //     (terminated)
		.pcs_writedata_10   (),                                           //     (terminated)
		.pcs_write_10       (),                                           //     (terminated)
		.pcs_waitrequest_10 (1'b0),                                       //     (terminated)
		.mac_address_11     (),                                           //     (terminated)
		.mac_readdata_11    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_11        (),                                           //     (terminated)
		.mac_writedata_11   (),                                           //     (terminated)
		.mac_write_11       (),                                           //     (terminated)
		.mac_waitrequest_11 (1'b0),                                       //     (terminated)
		.pcs_address_11     (),                                           //     (terminated)
		.pcs_readdata_11    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_11        (),                                           //     (terminated)
		.pcs_writedata_11   (),                                           //     (terminated)
		.pcs_write_11       (),                                           //     (terminated)
		.pcs_waitrequest_11 (1'b0),                                       //     (terminated)
		.mac_address_12     (),                                           //     (terminated)
		.mac_readdata_12    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_12        (),                                           //     (terminated)
		.mac_writedata_12   (),                                           //     (terminated)
		.mac_write_12       (),                                           //     (terminated)
		.mac_waitrequest_12 (1'b0),                                       //     (terminated)
		.pcs_address_12     (),                                           //     (terminated)
		.pcs_readdata_12    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_12        (),                                           //     (terminated)
		.pcs_writedata_12   (),                                           //     (terminated)
		.pcs_write_12       (),                                           //     (terminated)
		.pcs_waitrequest_12 (1'b0),                                       //     (terminated)
		.mac_address_13     (),                                           //     (terminated)
		.mac_readdata_13    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_13        (),                                           //     (terminated)
		.mac_writedata_13   (),                                           //     (terminated)
		.mac_write_13       (),                                           //     (terminated)
		.mac_waitrequest_13 (1'b0),                                       //     (terminated)
		.pcs_address_13     (),                                           //     (terminated)
		.pcs_readdata_13    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_13        (),                                           //     (terminated)
		.pcs_writedata_13   (),                                           //     (terminated)
		.pcs_write_13       (),                                           //     (terminated)
		.pcs_waitrequest_13 (1'b0),                                       //     (terminated)
		.mac_address_14     (),                                           //     (terminated)
		.mac_readdata_14    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_14        (),                                           //     (terminated)
		.mac_writedata_14   (),                                           //     (terminated)
		.mac_write_14       (),                                           //     (terminated)
		.mac_waitrequest_14 (1'b0),                                       //     (terminated)
		.pcs_address_14     (),                                           //     (terminated)
		.pcs_readdata_14    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_14        (),                                           //     (terminated)
		.pcs_writedata_14   (),                                           //     (terminated)
		.pcs_write_14       (),                                           //     (terminated)
		.pcs_waitrequest_14 (1'b0),                                       //     (terminated)
		.mac_address_15     (),                                           //     (terminated)
		.mac_readdata_15    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_15        (),                                           //     (terminated)
		.mac_writedata_15   (),                                           //     (terminated)
		.mac_write_15       (),                                           //     (terminated)
		.mac_waitrequest_15 (1'b0),                                       //     (terminated)
		.pcs_address_15     (),                                           //     (terminated)
		.pcs_readdata_15    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_15        (),                                           //     (terminated)
		.pcs_writedata_15   (),                                           //     (terminated)
		.pcs_write_15       (),                                           //     (terminated)
		.pcs_waitrequest_15 (1'b0),                                       //     (terminated)
		.mac_address_16     (),                                           //     (terminated)
		.mac_readdata_16    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_16        (),                                           //     (terminated)
		.mac_writedata_16   (),                                           //     (terminated)
		.mac_write_16       (),                                           //     (terminated)
		.mac_waitrequest_16 (1'b0),                                       //     (terminated)
		.pcs_address_16     (),                                           //     (terminated)
		.pcs_readdata_16    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_16        (),                                           //     (terminated)
		.pcs_writedata_16   (),                                           //     (terminated)
		.pcs_write_16       (),                                           //     (terminated)
		.pcs_waitrequest_16 (1'b0),                                       //     (terminated)
		.mac_address_17     (),                                           //     (terminated)
		.mac_readdata_17    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_17        (),                                           //     (terminated)
		.mac_writedata_17   (),                                           //     (terminated)
		.mac_write_17       (),                                           //     (terminated)
		.mac_waitrequest_17 (1'b0),                                       //     (terminated)
		.pcs_address_17     (),                                           //     (terminated)
		.pcs_readdata_17    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_17        (),                                           //     (terminated)
		.pcs_writedata_17   (),                                           //     (terminated)
		.pcs_write_17       (),                                           //     (terminated)
		.pcs_waitrequest_17 (1'b0),                                       //     (terminated)
		.mac_address_18     (),                                           //     (terminated)
		.mac_readdata_18    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_18        (),                                           //     (terminated)
		.mac_writedata_18   (),                                           //     (terminated)
		.mac_write_18       (),                                           //     (terminated)
		.mac_waitrequest_18 (1'b0),                                       //     (terminated)
		.pcs_address_18     (),                                           //     (terminated)
		.pcs_readdata_18    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_18        (),                                           //     (terminated)
		.pcs_writedata_18   (),                                           //     (terminated)
		.pcs_write_18       (),                                           //     (terminated)
		.pcs_waitrequest_18 (1'b0),                                       //     (terminated)
		.mac_address_19     (),                                           //     (terminated)
		.mac_readdata_19    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_19        (),                                           //     (terminated)
		.mac_writedata_19   (),                                           //     (terminated)
		.mac_write_19       (),                                           //     (terminated)
		.mac_waitrequest_19 (1'b0),                                       //     (terminated)
		.pcs_address_19     (),                                           //     (terminated)
		.pcs_readdata_19    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_19        (),                                           //     (terminated)
		.pcs_writedata_19   (),                                           //     (terminated)
		.pcs_write_19       (),                                           //     (terminated)
		.pcs_waitrequest_19 (1'b0),                                       //     (terminated)
		.mac_address_20     (),                                           //     (terminated)
		.mac_readdata_20    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_20        (),                                           //     (terminated)
		.mac_writedata_20   (),                                           //     (terminated)
		.mac_write_20       (),                                           //     (terminated)
		.mac_waitrequest_20 (1'b0),                                       //     (terminated)
		.pcs_address_20     (),                                           //     (terminated)
		.pcs_readdata_20    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_20        (),                                           //     (terminated)
		.pcs_writedata_20   (),                                           //     (terminated)
		.pcs_write_20       (),                                           //     (terminated)
		.pcs_waitrequest_20 (1'b0),                                       //     (terminated)
		.mac_address_21     (),                                           //     (terminated)
		.mac_readdata_21    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_21        (),                                           //     (terminated)
		.mac_writedata_21   (),                                           //     (terminated)
		.mac_write_21       (),                                           //     (terminated)
		.mac_waitrequest_21 (1'b0),                                       //     (terminated)
		.pcs_address_21     (),                                           //     (terminated)
		.pcs_readdata_21    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_21        (),                                           //     (terminated)
		.pcs_writedata_21   (),                                           //     (terminated)
		.pcs_write_21       (),                                           //     (terminated)
		.pcs_waitrequest_21 (1'b0),                                       //     (terminated)
		.mac_address_22     (),                                           //     (terminated)
		.mac_readdata_22    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_22        (),                                           //     (terminated)
		.mac_writedata_22   (),                                           //     (terminated)
		.mac_write_22       (),                                           //     (terminated)
		.mac_waitrequest_22 (1'b0),                                       //     (terminated)
		.pcs_address_22     (),                                           //     (terminated)
		.pcs_readdata_22    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_22        (),                                           //     (terminated)
		.pcs_writedata_22   (),                                           //     (terminated)
		.pcs_write_22       (),                                           //     (terminated)
		.pcs_waitrequest_22 (1'b0),                                       //     (terminated)
		.mac_address_23     (),                                           //     (terminated)
		.mac_readdata_23    (32'b00000000000000000000000000000000),       //     (terminated)
		.mac_read_23        (),                                           //     (terminated)
		.mac_writedata_23   (),                                           //     (terminated)
		.mac_write_23       (),                                           //     (terminated)
		.mac_waitrequest_23 (1'b0),                                       //     (terminated)
		.pcs_address_23     (),                                           //     (terminated)
		.pcs_readdata_23    (16'b0000000000000000),                       //     (terminated)
		.pcs_read_23        (),                                           //     (terminated)
		.pcs_writedata_23   (),                                           //     (terminated)
		.pcs_write_23       (),                                           //     (terminated)
		.pcs_waitrequest_23 (1'b0)                                        //     (terminated)
	);

	altera_eth_tse_channel_adapter #(
		.MAX_CHANNELS  (1),
		.CHANNEL_WIDTH (1)
	) channel_adapter (
		.clk                   (rx_afull_clk),                        //           clk.clk
		.reset                 (rst_controller_reset_out_reset),      //         reset.reset
		.rx_afull_data         (rx_afull_data),                       //    channel_in.data
		.rx_afull_valid        (rx_afull_valid),                      //              .valid
		.rx_afull_channel      (rx_afull_channel),                    //              .channel
		.rx_afull_data_out_0   (channel_adapter_channel_out_0_data),  // channel_out_0.data
		.rx_afull_valid_out_0  (channel_adapter_channel_out_0_valid), //              .valid
		.rx_afull_data_out_1   (),                                    //   (terminated)
		.rx_afull_valid_out_1  (),                                    //   (terminated)
		.rx_afull_data_out_2   (),                                    //   (terminated)
		.rx_afull_valid_out_2  (),                                    //   (terminated)
		.rx_afull_data_out_3   (),                                    //   (terminated)
		.rx_afull_valid_out_3  (),                                    //   (terminated)
		.rx_afull_data_out_4   (),                                    //   (terminated)
		.rx_afull_valid_out_4  (),                                    //   (terminated)
		.rx_afull_data_out_5   (),                                    //   (terminated)
		.rx_afull_valid_out_5  (),                                    //   (terminated)
		.rx_afull_data_out_6   (),                                    //   (terminated)
		.rx_afull_valid_out_6  (),                                    //   (terminated)
		.rx_afull_data_out_7   (),                                    //   (terminated)
		.rx_afull_valid_out_7  (),                                    //   (terminated)
		.rx_afull_data_out_8   (),                                    //   (terminated)
		.rx_afull_valid_out_8  (),                                    //   (terminated)
		.rx_afull_data_out_9   (),                                    //   (terminated)
		.rx_afull_valid_out_9  (),                                    //   (terminated)
		.rx_afull_data_out_10  (),                                    //   (terminated)
		.rx_afull_valid_out_10 (),                                    //   (terminated)
		.rx_afull_data_out_11  (),                                    //   (terminated)
		.rx_afull_valid_out_11 (),                                    //   (terminated)
		.rx_afull_data_out_12  (),                                    //   (terminated)
		.rx_afull_valid_out_12 (),                                    //   (terminated)
		.rx_afull_data_out_13  (),                                    //   (terminated)
		.rx_afull_valid_out_13 (),                                    //   (terminated)
		.rx_afull_data_out_14  (),                                    //   (terminated)
		.rx_afull_valid_out_14 (),                                    //   (terminated)
		.rx_afull_data_out_15  (),                                    //   (terminated)
		.rx_afull_valid_out_15 (),                                    //   (terminated)
		.rx_afull_data_out_16  (),                                    //   (terminated)
		.rx_afull_valid_out_16 (),                                    //   (terminated)
		.rx_afull_data_out_17  (),                                    //   (terminated)
		.rx_afull_valid_out_17 (),                                    //   (terminated)
		.rx_afull_data_out_18  (),                                    //   (terminated)
		.rx_afull_valid_out_18 (),                                    //   (terminated)
		.rx_afull_data_out_19  (),                                    //   (terminated)
		.rx_afull_valid_out_19 (),                                    //   (terminated)
		.rx_afull_data_out_20  (),                                    //   (terminated)
		.rx_afull_valid_out_20 (),                                    //   (terminated)
		.rx_afull_data_out_21  (),                                    //   (terminated)
		.rx_afull_valid_out_21 (),                                    //   (terminated)
		.rx_afull_data_out_22  (),                                    //   (terminated)
		.rx_afull_valid_out_22 (),                                    //   (terminated)
		.rx_afull_data_out_23  (),                                    //   (terminated)
		.rx_afull_valid_out_23 ()                                     //   (terminated)
	);

	altera_eth_tse_fifoless_mac #(
		.ENABLE_MAC_RX_VLAN       (0),
		.ENABLE_SUP_ADDR          (0),
		.DEVICE_FAMILY            ("CYCLONEV"),
		.ENABLE_ECC               (0),
		.CRC32DWIDTH              (8),
		.SYNCHRONIZER_DEPTH       (3),
		.ENABLE_MAC_TX_VLAN       (0),
		.RESET_LEVEL              (1),
		.STAT_CNT_ENA             (0),
		.CUST_VERSION             (0),
		.CRC32S1L2_EXTERN         (0),
		.MBIT_ONLY                (1),
		.ENABLE_PTP_1STEP         (0),
		.CORE_VERSION             (5633),
		.CRC32GENDELAY            (6),
		.FINGERPRINT_WIDTH        (4),
		.ENABLE_REG_SHARING       (0),
		.REDUCED_INTERFACE_ENA    (0),
		.ENABLE_MAGIC_DETECT      (0),
		.ENABLE_MDIO              (0),
		.ENABLE_TIMESTAMPING      (0),
		.ENABLE_MAC_TXADDR_SET    (1),
		.CRC32CHECK16BIT          (0),
		.MAC_ONLY                 (0),
		.ENABLE_LGTH_CHECK        (1),
		.ENABLE_MAC_FLOW_CTRL     (0),
		.ENABLE_SHIFT16           (0),
		.USE_SYNC_RESET           (1),
		.REDUCED_CONTROL          (0),
		.MDIO_CLK_DIV             (40),
		.ENABLE_PADDING           (1),
		.ENABLE_GMII_LOOPBACK     (0),
		.GBIT_ONLY                (1),
		.ENA_HASH                 (0),
		.ENABLE_EXTENDED_STAT_REG (0),
		.ENABLE_HD_LOGIC          (0)
	) i_tse_fifoless_mac_0 (
		.reg_clk                                        (clk),                                                                                                  //        control_port_clock_connection.clk
		.reset                                          (reset),                                                                                                //                     reset_connection.reset
		.reg_addr                                       (avalon_arbiter_av_mac_master_0_address),                                                               //                         control_port.address
		.reg_data_out                                   (avalon_arbiter_av_mac_master_0_readdata),                                                              //                                     .readdata
		.reg_rd                                         (avalon_arbiter_av_mac_master_0_read),                                                                  //                                     .read
		.reg_data_in                                    (avalon_arbiter_av_mac_master_0_writedata),                                                             //                                     .writedata
		.reg_wr                                         (avalon_arbiter_av_mac_master_0_write),                                                                 //                                     .write
		.reg_busy                                       (avalon_arbiter_av_mac_master_0_waitrequest),                                                           //                                     .waitrequest
		.mac_rx_clk                                     (mac_rx_clk_0),                                                                                         //              mac_rx_clock_connection.clk
		.mac_tx_clk                                     (mac_tx_clk_0),                                                                                         //              mac_tx_clock_connection.clk
		.data_rx_data                                   (data_rx_data_0),                                                                                       //                              receive.data
		.data_rx_eop                                    (data_rx_eop_0),                                                                                        //                                     .endofpacket
		.data_rx_error                                  (data_rx_error_0),                                                                                      //                                     .error
		.data_rx_ready                                  (data_rx_ready_0),                                                                                      //                                     .ready
		.data_rx_sop                                    (data_rx_sop_0),                                                                                        //                                     .startofpacket
		.data_rx_valid                                  (data_rx_valid_0),                                                                                      //                                     .valid
		.data_tx_data                                   (data_tx_data_0),                                                                                       //                             transmit.data
		.data_tx_eop                                    (data_tx_eop_0),                                                                                        //                                     .endofpacket
		.data_tx_error                                  (data_tx_error_0),                                                                                      //                                     .error
		.data_tx_ready                                  (data_tx_ready_0),                                                                                      //                                     .ready
		.data_tx_sop                                    (data_tx_sop_0),                                                                                        //                                     .startofpacket
		.data_tx_valid                                  (data_tx_valid_0),                                                                                      //                                     .valid
		.rx_afull_clk                                   (rx_afull_clk),                                                                                         // receive_fifo_status_clock_connection.clk
		.rx_afull_data                                  (channel_adapter_channel_out_0_data),                                                                   //                  receive_fifo_status.data
		.rx_afull_valid                                 (channel_adapter_channel_out_0_valid),                                                                  //                                     .valid
		.pkt_class_data                                 (pkt_class_data_0),                                                                                     //                  receive_packet_type.data
		.pkt_class_valid                                (pkt_class_valid_0),                                                                                    //                                     .valid
		.tx_crc_fwd                                     (tx_crc_fwd_0),                                                                                         //                  mac_misc_connection.export
		.gm_rx_d                                        (i_tse_pcs_0_gmii_connection_gmii_rx_d),                                                                //                  mac_gmii_connection.gmii_rx_d
		.gm_rx_dv                                       (i_tse_pcs_0_gmii_connection_gmii_rx_dv),                                                               //                                     .gmii_rx_dv
		.gm_rx_err                                      (i_tse_pcs_0_gmii_connection_gmii_rx_err),                                                              //                                     .gmii_rx_err
		.gm_tx_d                                        (i_tse_fifoless_mac_0_mac_gmii_connection_gmii_tx_d),                                                   //                                     .gmii_tx_d
		.gm_tx_en                                       (i_tse_fifoless_mac_0_mac_gmii_connection_gmii_tx_en),                                                  //                                     .gmii_tx_en
		.gm_tx_err                                      (i_tse_fifoless_mac_0_mac_gmii_connection_gmii_tx_err),                                                 //                                     .gmii_tx_err
		.m_rx_d                                         (i_tse_pcs_0_mii_connection_mii_rx_d),                                                                  //                   mac_mii_connection.mii_rx_d
		.m_rx_en                                        (i_tse_pcs_0_mii_connection_mii_rx_dv),                                                                 //                                     .mii_rx_dv
		.m_rx_err                                       (i_tse_pcs_0_mii_connection_mii_rx_err),                                                                //                                     .mii_rx_err
		.m_tx_d                                         (i_tse_fifoless_mac_0_mac_mii_connection_mii_tx_d),                                                     //                                     .mii_tx_d
		.m_tx_en                                        (i_tse_fifoless_mac_0_mac_mii_connection_mii_tx_en),                                                    //                                     .mii_tx_en
		.m_tx_err                                       (i_tse_fifoless_mac_0_mac_mii_connection_mii_tx_err),                                                   //                                     .mii_tx_err
		.m_rx_crs                                       (i_tse_pcs_0_mii_connection_mii_crs),                                                                   //                                     .mii_crs
		.m_rx_col                                       (i_tse_pcs_0_mii_connection_mii_col),                                                                   //                                     .mii_col
		.set_10                                         (i_tse_pcs_0_sgmii_status_connection_set_10),                                                           //                mac_status_connection.set_10
		.set_1000                                       (i_tse_pcs_0_sgmii_status_connection_set_1000),                                                         //                                     .set_1000
		.rx_clkena                                      (i_tse_pcs_0_clock_enable_connection_rx_clkena),                                                        //                mac_clkena_connection.rx_clkena
		.tx_clkena                                      (i_tse_pcs_0_clock_enable_connection_tx_clkena),                                                        //                                     .tx_clkena
		.tx_clk                                         (i_tse_pcs_0_pcs_transmit_clock_connection_clk),                                                        //          pcs_mac_tx_clock_connection.clk
		.rx_clk                                         (i_tse_pcs_0_pcs_receive_clock_connection_clk),                                                         //          pcs_mac_rx_clock_connection.clk
		.magic_sleep_n                                  (1'b1),                                                                                                 //                          (terminated)
		.xon_gen                                        (1'b0),                                                                                                 //                          (terminated)
		.xoff_gen                                       (1'b0),                                                                                                 //                          (terminated)
		.magic_wakeup                                   (),                                                                                                     //                          (terminated)
		.tx_ff_uflow                                    (),                                                                                                     //                          (terminated)
		.mac_eccstatus                                  (),                                                                                                     //                          (terminated)
		.pause_quant_out                                (),                                                                                                     //                          (terminated)
		.frm_length_max_out                             (),                                                                                                     //                          (terminated)
		.tx_ipg_len_out                                 (),                                                                                                     //                          (terminated)
		.pause_quant_in                                 (16'b0000000000000000),                                                                                 //                          (terminated)
		.frm_length_max_in                              (16'b0000000000000000),                                                                                 //                          (terminated)
		.tx_ipg_len_in                                  (5'b00000),                                                                                             //                          (terminated)
		.mdc                                            (),                                                                                                     //                          (terminated)
		.mdio_in                                        (1'b0),                                                                                                 //                          (terminated)
		.mdio_out                                       (),                                                                                                     //                          (terminated)
		.mdio_oen                                       (),                                                                                                     //                          (terminated)
		.rgmii_out1_aclr                                (),                                                                                                     //                          (terminated)
		.rgmii_out1_din                                 (),                                                                                                     //                          (terminated)
		.rgmii_in1_dout                                 (2'b00),                                                                                                //                          (terminated)
		.rgmii_in1_ck                                   (),                                                                                                     //                          (terminated)
		.rgmii_out4_din                                 (),                                                                                                     //                          (terminated)
		.rgmii_out4_ck                                  (),                                                                                                     //                          (terminated)
		.rgmii_in1_pad                                  (),                                                                                                     //                          (terminated)
		.rgmii_out4_aclr                                (),                                                                                                     //                          (terminated)
		.rgmii_out1_pad                                 (1'b0),                                                                                                 //                          (terminated)
		.rgmii_out1_ck                                  (),                                                                                                     //                          (terminated)
		.rgmii_in4_dout                                 (8'b00000000),                                                                                          //                          (terminated)
		.rgmii_in4_pad                                  (),                                                                                                     //                          (terminated)
		.rgmii_out4_pad                                 (4'b0000),                                                                                              //                          (terminated)
		.rgmii_in4_ck                                   (),                                                                                                     //                          (terminated)
		.rgmii_in                                       (4'b0000),                                                                                              //                          (terminated)
		.rgmii_out                                      (),                                                                                                     //                          (terminated)
		.rx_control                                     (1'b0),                                                                                                 //                          (terminated)
		.tx_control                                     (),                                                                                                     //                          (terminated)
		.eth_mode                                       (),                                                                                                     //                          (terminated)
		.ena_10                                         (),                                                                                                     //                          (terminated)
		.tx_egress_timestamp_request_valid              (1'b0),                                                                                                 //                          (terminated)
		.tx_egress_timestamp_request_fingerprint        (4'b0000),                                                                                              //                          (terminated)
		.tx_etstamp_ins_ctrl_timestamp_insert           (1'b0),                                                                                                 //                          (terminated)
		.tx_etstamp_ins_ctrl_residence_time_update      (1'b0),                                                                                                 //                          (terminated)
		.tx_etstamp_ins_ctrl_checksum_zero              (1'b0),                                                                                                 //                          (terminated)
		.tx_etstamp_ins_ctrl_checksum_correct           (1'b0),                                                                                                 //                          (terminated)
		.tx_etstamp_ins_ctrl_residence_time_calc_format (1'b0),                                                                                                 //                          (terminated)
		.tx_etstamp_ins_ctrl_timestamp_format           (1'b0),                                                                                                 //                          (terminated)
		.tx_etstamp_ins_ctrl_offset_timestamp           (16'b0000000000000000),                                                                                 //                          (terminated)
		.tx_etstamp_ins_ctrl_offset_correction_field    (16'b0000000000000000),                                                                                 //                          (terminated)
		.tx_etstamp_ins_ctrl_offset_checksum_field      (16'b0000000000000000),                                                                                 //                          (terminated)
		.tx_etstamp_ins_ctrl_offset_checksum_correction (16'b0000000000000000),                                                                                 //                          (terminated)
		.tx_etstamp_ins_ctrl_ingress_timestamp_96b      (96'b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000), //                          (terminated)
		.tx_etstamp_ins_ctrl_ingress_timestamp_64b      (64'b0000000000000000000000000000000000000000000000000000000000000000),                                 //                          (terminated)
		.tx_path_delay_data                             (22'b0000000000000000000000),                                                                           //                          (terminated)
		.rx_path_delay_data                             (22'b0000000000000000000000),                                                                           //                          (terminated)
		.tx_time_of_day_96b_data                        (96'b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000), //                          (terminated)
		.tx_time_of_day_64b_data                        (64'b0000000000000000000000000000000000000000000000000000000000000000),                                 //                          (terminated)
		.rx_time_of_day_96b_data                        (96'b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000), //                          (terminated)
		.rx_time_of_day_64b_data                        (64'b0000000000000000000000000000000000000000000000000000000000000000),                                 //                          (terminated)
		.tx_egress_timestamp_96b_valid                  (),                                                                                                     //                          (terminated)
		.tx_egress_timestamp_96b_data                   (),                                                                                                     //                          (terminated)
		.tx_egress_timestamp_96b_fingerprint            (),                                                                                                     //                          (terminated)
		.tx_egress_timestamp_64b_valid                  (),                                                                                                     //                          (terminated)
		.tx_egress_timestamp_64b_data                   (),                                                                                                     //                          (terminated)
		.tx_egress_timestamp_64b_fingerprint            (),                                                                                                     //                          (terminated)
		.rx_ingress_timestamp_96b_valid                 (),                                                                                                     //                          (terminated)
		.rx_ingress_timestamp_96b_data                  (),                                                                                                     //                          (terminated)
		.rx_ingress_timestamp_64b_valid                 (),                                                                                                     //                          (terminated)
		.rx_ingress_timestamp_64b_data                  (),                                                                                                     //                          (terminated)
		.tx_ptp_alignment                               (1'b0)                                                                                                  //                          (terminated)
	);

	altera_eth_tse_pcs_pma_phyip #(
		.ENABLE_TIMESTAMPING (0),
		.DEV_VERSION         (5633),
		.ENABLE_ECC          (0),
		.DEVICE_FAMILY       ("CYCLONEV"),
		.SYNCHRONIZER_DEPTH  (3),
		.ENABLE_CLK_SHARING  (1),
		.ENABLE_SGMII        (0),
		.PHY_IDENTIFIER      (0)
	) i_tse_pcs_0 (
		.clk                   (clk),                                                  // control_port_clock_connection.clk
		.reset                 (reset),                                                //              reset_connection.reset
		.reg_addr              (avalon_arbiter_av_pcs_master_0_address),               //                  control_port.address
		.reg_data_out          (avalon_arbiter_av_pcs_master_0_readdata),              //                              .readdata
		.reg_rd                (avalon_arbiter_av_pcs_master_0_read),                  //                              .read
		.reg_data_in           (avalon_arbiter_av_pcs_master_0_writedata),             //                              .writedata
		.reg_wr                (avalon_arbiter_av_pcs_master_0_write),                 //                              .write
		.reg_busy              (avalon_arbiter_av_pcs_master_0_waitrequest),           //                              .waitrequest
		.ref_clk               (ref_clk),                                              //  pcs_ref_clk_clock_connection.clk
		.rx_pcs_clk            (i_custom_phyip_0_rx_clkout_export),                    //                    rx_pcs_clk.export
		.sd_loopback           (i_tse_pcs_0_sd_loopback_export),                       //                   sd_loopback.export
		.rx_disp_err           (i_custom_phyip_0_rx_disperr_export),                   //                   rx_disp_err.export
		.tx_pcs_clk            (i_custom_phyip_0_tx_clkout_export),                    //                    tx_pcs_clk.export
		.rx_runningdisp        (i_custom_phyip_0_rx_runningdisp_export),               //                rx_runningdisp.export
		.rx_frame              (i_custom_phyip_0_rx_parallel_data_export),             //                      rx_frame.export
		.rx_runlengthviolation (i_custom_phyip_0_rx_rlv_export),                       //         rx_runlengthviolation.export
		.rx_char_err_gx        (i_custom_phyip_0_rx_errdetect_export),                 //                rx_char_err_gx.export
		.tx_frame              (i_tse_pcs_0_tx_frame_export),                          //                      tx_frame.export
		.rx_patterndetect      (i_custom_phyip_0_rx_patterndetect_export),             //              rx_patterndetect.export
		.rx_kchar              (i_custom_phyip_0_rx_datak_export),                     //                      rx_kchar.export
		.rx_syncstatus         (i_custom_phyip_0_rx_syncstatus_export),                //                 rx_syncstatus.export
		.tx_kchar              (i_tse_pcs_0_tx_kchar_export),                          //                      tx_kchar.export
		.rx_rmfifodatadeleted  (i_custom_phyip_0_rx_rmfifodatadeleted_export),         //          rx_rmfifodatadeleted.export
		.rx_rmfifodatainserted (i_custom_phyip_0_rx_rmfifodatainserted_export),        //         rx_rmfifodatainserted.export
		.tx_clkena             (i_tse_pcs_0_clock_enable_connection_tx_clkena),        //       clock_enable_connection.tx_clkena
		.rx_clkena             (i_tse_pcs_0_clock_enable_connection_rx_clkena),        //                              .rx_clkena
		.gmii_rx_dv            (i_tse_pcs_0_gmii_connection_gmii_rx_dv),               //               gmii_connection.gmii_rx_dv
		.gmii_rx_d             (i_tse_pcs_0_gmii_connection_gmii_rx_d),                //                              .gmii_rx_d
		.gmii_rx_err           (i_tse_pcs_0_gmii_connection_gmii_rx_err),              //                              .gmii_rx_err
		.gmii_tx_en            (i_tse_fifoless_mac_0_mac_gmii_connection_gmii_tx_en),  //                              .gmii_tx_en
		.gmii_tx_d             (i_tse_fifoless_mac_0_mac_gmii_connection_gmii_tx_d),   //                              .gmii_tx_d
		.gmii_tx_err           (i_tse_fifoless_mac_0_mac_gmii_connection_gmii_tx_err), //                              .gmii_tx_err
		.mii_rx_dv             (i_tse_pcs_0_mii_connection_mii_rx_dv),                 //                mii_connection.mii_rx_dv
		.mii_rx_d              (i_tse_pcs_0_mii_connection_mii_rx_d),                  //                              .mii_rx_d
		.mii_rx_err            (i_tse_pcs_0_mii_connection_mii_rx_err),                //                              .mii_rx_err
		.mii_tx_en             (i_tse_fifoless_mac_0_mac_mii_connection_mii_tx_en),    //                              .mii_tx_en
		.mii_tx_d              (i_tse_fifoless_mac_0_mac_mii_connection_mii_tx_d),     //                              .mii_tx_d
		.mii_tx_err            (i_tse_fifoless_mac_0_mac_mii_connection_mii_tx_err),   //                              .mii_tx_err
		.mii_col               (i_tse_pcs_0_mii_connection_mii_col),                   //                              .mii_col
		.mii_crs               (i_tse_pcs_0_mii_connection_mii_crs),                   //                              .mii_crs
		.set_10                (i_tse_pcs_0_sgmii_status_connection_set_10),           //       sgmii_status_connection.set_10
		.set_1000              (i_tse_pcs_0_sgmii_status_connection_set_1000),         //                              .set_1000
		.tx_clk                (i_tse_pcs_0_pcs_transmit_clock_connection_clk),        // pcs_transmit_clock_connection.clk
		.rx_clk                (i_tse_pcs_0_pcs_receive_clock_connection_clk),         //  pcs_receive_clock_connection.clk
		.reset_tx_clk          (rst_controller_001_reset_out_reset),                   // pcs_transmit_reset_connection.reset
		.reset_rx_clk          (rst_controller_002_reset_out_reset),                   //  pcs_receive_reset_connection.reset
		.led_crs               (led_crs_0),                                            //         status_led_connection.export
		.led_link              (led_link_0),                                           //                              .export
		.led_panel_link        (led_panel_link_0),                                     //                              .export
		.led_col               (led_col_0),                                            //                              .export
		.led_an                (led_an_0),                                             //                              .export
		.led_char_err          (led_char_err_0),                                       //                              .export
		.led_disp_err          (led_disp_err_0),                                       //                              .export
		.wa_boundary           (i_custom_phyip_0_rx_bitslipboundaryselectout_export),  //                   wa_boundary.export
		.set_100               (),                                                     //                   (terminated)
		.hd_ena                (),                                                     //                   (terminated)
		.pcs_phase_measure_clk (1'b0),                                                 //                   (terminated)
		.rx_latency_adj        (),                                                     //                   (terminated)
		.tx_latency_adj        (),                                                     //                   (terminated)
		.tx_ptp_alignment      (),                                                     //                   (terminated)
		.pcs_eccstatus         ()                                                      //                   (terminated)
	);

	altera_xcvr_custom #(
		.device_family                         ("Cyclone V"),
		.protocol_hint                         ("gige"),
		.operation_mode                        ("Duplex"),
		.lanes                                 (1),
		.bonded_group_size                     (1),
		.bonded_mode                           ("xN"),
		.pma_bonding_mode                      ("x1"),
		.pcs_pma_width                         (10),
		.ser_base_factor                       (8),
		.ser_words                             (1),
		.data_rate                             ("1250 Mbps"),
		.base_data_rate                        ("1250 Mbps"),
		.en_synce_support                      (0),
		.tx_bitslip_enable                     ("false"),
		.rx_use_coreclk                        ("false"),
		.tx_use_coreclk                        ("false"),
		.use_8b10b                             ("true"),
		.use_8b10b_manual_control              ("false"),
		.std_tx_pcfifo_mode                    ("low_latency"),
		.std_rx_pcfifo_mode                    ("low_latency"),
		.word_aligner_mode                     ("sync_state_machine"),
		.word_aligner_state_machine_datacnt    (3),
		.word_aligner_state_machine_errcnt     (4),
		.word_aligner_state_machine_patterncnt (4),
		.word_aligner_pattern_length           (7),
		.word_align_pattern                    ("1111100"),
		.run_length_violation_checking         (5),
		.use_rate_match_fifo                   (1),
		.rate_match_pattern1                   ("10100010010101111100"),
		.rate_match_pattern2                   ("10101011011010000011"),
		.byte_order_mode                       ("none"),
		.byte_order_pattern                    ("111111011"),
		.byte_order_pad_pattern                ("000000000"),
		.coreclk_0ppm_enable                   ("false"),
		.pll_refclk_cnt                        (1),
		.pll_refclk_freq                       ("125.0 MHz"),
		.pll_refclk_select                     ("0"),
		.cdr_refclk_select                     (0),
		.plls                                  (1),
		.pll_type                              ("CMU"),
		.pll_select                            (0),
		.pll_reconfig                          (0),
		.pll_external_enable                   (0),
		.gxb_analog_power                      ("AUTO"),
		.pll_lock_speed                        ("AUTO"),
		.tx_analog_power                       ("AUTO"),
		.tx_slew_rate                          ("OFF"),
		.tx_termination                        ("OCT_100_OHMS"),
		.tx_use_external_termination           ("false"),
		.tx_preemp_pretap                      (0),
		.tx_preemp_pretap_inv                  ("false"),
		.tx_preemp_tap_1                       (0),
		.tx_preemp_tap_2                       (0),
		.tx_preemp_tap_2_inv                   ("false"),
		.tx_vod_selection                      (2),
		.tx_common_mode                        ("0.65V"),
		.rx_pll_lock_speed                     ("AUTO"),
		.rx_common_mode                        ("0.82V"),
		.rx_termination                        ("OCT_100_OHMS"),
		.rx_use_external_termination           ("false"),
		.rx_eq_dc_gain                         (1),
		.rx_eq_ctrl                            (16),
		.mgmt_clk_in_mhz                       (250),
		.embedded_reset                        (1),
		.channel_interface                     (0)
	) i_custom_phyip_0 (
		.phy_mgmt_clk                (clk),                                                    //                phy_mgmt_clk.clk
		.phy_mgmt_clk_reset          (reset),                                                  //          phy_mgmt_clk_reset.reset
		.phy_mgmt_address            (i_phyip_terminator_0_av_dummy_master_address),           //                    phy_mgmt.address
		.phy_mgmt_read               (i_phyip_terminator_0_av_dummy_master_read),              //                            .read
		.phy_mgmt_readdata           (i_phyip_terminator_0_av_dummy_master_readdata),          //                            .readdata
		.phy_mgmt_waitrequest        (i_phyip_terminator_0_av_dummy_master_waitrequest),       //                            .waitrequest
		.phy_mgmt_write              (i_phyip_terminator_0_av_dummy_master_write),             //                            .write
		.phy_mgmt_writedata          (i_phyip_terminator_0_av_dummy_master_writedata),         //                            .writedata
		.tx_ready                    (i_custom_phyip_0_tx_ready_export),                       //                    tx_ready.export
		.rx_ready                    (i_custom_phyip_0_rx_ready_export),                       //                    rx_ready.export
		.pll_ref_clk                 (ref_clk),                                                //                 pll_ref_clk.clk
		.tx_serial_data              (i_custom_phyip_0_tx_serial_data_export),                 //              tx_serial_data.export
		.pll_locked                  (i_custom_phyip_0_pll_locked_export),                     //                  pll_locked.export
		.rx_serial_data              (i_phyip_terminator_0_rx_serial_data_export),             //              rx_serial_data.export
		.rx_runningdisp              (i_custom_phyip_0_rx_runningdisp_export),                 //              rx_runningdisp.export
		.rx_disperr                  (i_custom_phyip_0_rx_disperr_export),                     //                  rx_disperr.export
		.rx_errdetect                (i_custom_phyip_0_rx_errdetect_export),                   //                rx_errdetect.export
		.rx_patterndetect            (i_custom_phyip_0_rx_patterndetect_export),               //            rx_patterndetect.export
		.rx_syncstatus               (i_custom_phyip_0_rx_syncstatus_export),                  //               rx_syncstatus.export
		.rx_bitslipboundaryselectout (i_custom_phyip_0_rx_bitslipboundaryselectout_export),    // rx_bitslipboundaryselectout.export
		.rx_rmfifodatainserted       (i_custom_phyip_0_rx_rmfifodatainserted_export),          //       rx_rmfifodatainserted.export
		.rx_rmfifodatadeleted        (i_custom_phyip_0_rx_rmfifodatadeleted_export),           //        rx_rmfifodatadeleted.export
		.rx_rlv                      (i_custom_phyip_0_rx_rlv_export),                         //                      rx_rlv.export
		.rx_recovered_clk            (i_custom_phyip_0_rx_recovered_clk_export),               //            rx_recovered_clk.export
		.tx_clkout                   (i_custom_phyip_0_tx_clkout_export),                      //                   tx_clkout.export
		.rx_clkout                   (i_custom_phyip_0_rx_clkout_export),                      //                   rx_clkout.export
		.tx_parallel_data            (i_tse_pcs_0_tx_frame_export),                            //            tx_parallel_data.export
		.tx_datak                    (i_tse_pcs_0_tx_kchar_export),                            //                    tx_datak.export
		.rx_parallel_data            (i_custom_phyip_0_rx_parallel_data_export),               //            rx_parallel_data.export
		.rx_datak                    (i_custom_phyip_0_rx_datak_export),                       //                    rx_datak.export
		.reconfig_from_xcvr          (i_custom_phyip_0_reconfig_from_xcvr_reconfig_from_xcvr), //          reconfig_from_xcvr.reconfig_from_xcvr
		.reconfig_to_xcvr            (i_phyip_terminator_0_reconfig_to_xcvr_reconfig_to_xcvr), //            reconfig_to_xcvr.reconfig_to_xcvr
		.tx_forceelecidle            (1'b0),                                                   //                 (terminated)
		.tx_bitslipboundaryselect    (5'b00000),                                               //                 (terminated)
		.rx_is_lockedtoref           (),                                                       //                 (terminated)
		.rx_is_lockedtodata          (),                                                       //                 (terminated)
		.rx_signaldetect             (),                                                       //                 (terminated)
		.rx_enabyteord               (1'b0),                                                   //                 (terminated)
		.rx_bitslip                  (1'b0),                                                   //                 (terminated)
		.rx_byteordflag              (),                                                       //                 (terminated)
		.tx_coreclkin                (1'b0),                                                   //                 (terminated)
		.rx_coreclkin                (1'b0),                                                   //                 (terminated)
		.cdr_ref_clk                 (1'b0),                                                   //                 (terminated)
		.tx_dispval                  (1'b0),                                                   //                 (terminated)
		.tx_forcedisp                (1'b0),                                                   //                 (terminated)
		.pll_powerdown               (1'b0),                                                   //                 (terminated)
		.tx_digitalreset             (1'b0),                                                   //                 (terminated)
		.tx_analogreset              (1'b0),                                                   //                 (terminated)
		.tx_cal_busy                 (),                                                       //                 (terminated)
		.rx_digitalreset             (1'b0),                                                   //                 (terminated)
		.rx_analogreset              (1'b0),                                                   //                 (terminated)
		.rx_cal_busy                 (),                                                       //                 (terminated)
		.ext_pll_clk                 (1'b0)                                                    //                 (terminated)
	);

	altera_eth_tse_phyip_terminator #(
		.RECONFIG_TO_WIDTH   (140),
		.RECONFIG_FROM_WIDTH (92),
		.ENABLE_TIMESTAMPING (0)
	) i_phyip_terminator_0 (
		.clk                        (clk),                                                    //                       clk.clk
		.reset                      (reset),                                                  //                     reset.reset
		.address                    (i_phyip_terminator_0_av_dummy_master_address),           //           av_dummy_master.address
		.readdata                   (i_phyip_terminator_0_av_dummy_master_readdata),          //                          .readdata
		.read                       (i_phyip_terminator_0_av_dummy_master_read),              //                          .read
		.writedata                  (i_phyip_terminator_0_av_dummy_master_writedata),         //                          .writedata
		.write                      (i_phyip_terminator_0_av_dummy_master_write),             //                          .write
		.waitrequest                (i_phyip_terminator_0_av_dummy_master_waitrequest),       //                          .waitrequest
		.rxp                        (rxp_0),                                                  //         serial_connection.export
		.txp                        (txp_0),                                                  //                          .export
		.rx_recovclkout             (rx_recovclkout_0),                                       // serdes_control_connection.export
		.reconfig_togxb             (reconfig_togxb_0),                                       //                          .export
		.reconfig_fromgxb           (reconfig_fromgxb_0),                                     //                          .export
		.tx_ready                   (i_custom_phyip_0_tx_ready_export),                       //                  tx_ready.export
		.tx_serial_data             (i_custom_phyip_0_tx_serial_data_export),                 //            tx_serial_data.export
		.sd_loopback                (i_tse_pcs_0_sd_loopback_export),                         //               sd_loopback.export
		.rx_recovered_clk           (i_custom_phyip_0_rx_recovered_clk_export),               //          rx_recovered_clk.export
		.pll_locked                 (i_custom_phyip_0_pll_locked_export),                     //                pll_locked.export
		.rx_ready                   (i_custom_phyip_0_rx_ready_export),                       //                  rx_ready.export
		.rx_serial_data             (i_phyip_terminator_0_rx_serial_data_export),             //            rx_serial_data.export
		.reconfig_to_xcvr           (i_phyip_terminator_0_reconfig_to_xcvr_reconfig_to_xcvr), //          reconfig_to_xcvr.reconfig_to_xcvr
		.reconfig_from_xcvr         (i_custom_phyip_0_reconfig_from_xcvr_reconfig_from_xcvr), //        reconfig_from_xcvr.reconfig_from_xcvr
		.cdr_ref_clk_out            (),                                                       //               (terminated)
		.cdr_ref_clk_in             (1'b0),                                                   //               (terminated)
		.terminate_rx_recovered_clk (1'b0)                                                    //               (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (reset),                          // reset_in0.reset
		.clk            (rx_afull_clk),                   //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (reset),                                         // reset_in0.reset
		.clk            (i_tse_pcs_0_pcs_transmit_clock_connection_clk), //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),            // reset_out.reset
		.reset_req      (),                                              // (terminated)
		.reset_req_in0  (1'b0),                                          // (terminated)
		.reset_in1      (1'b0),                                          // (terminated)
		.reset_req_in1  (1'b0),                                          // (terminated)
		.reset_in2      (1'b0),                                          // (terminated)
		.reset_req_in2  (1'b0),                                          // (terminated)
		.reset_in3      (1'b0),                                          // (terminated)
		.reset_req_in3  (1'b0),                                          // (terminated)
		.reset_in4      (1'b0),                                          // (terminated)
		.reset_req_in4  (1'b0),                                          // (terminated)
		.reset_in5      (1'b0),                                          // (terminated)
		.reset_req_in5  (1'b0),                                          // (terminated)
		.reset_in6      (1'b0),                                          // (terminated)
		.reset_req_in6  (1'b0),                                          // (terminated)
		.reset_in7      (1'b0),                                          // (terminated)
		.reset_req_in7  (1'b0),                                          // (terminated)
		.reset_in8      (1'b0),                                          // (terminated)
		.reset_req_in8  (1'b0),                                          // (terminated)
		.reset_in9      (1'b0),                                          // (terminated)
		.reset_req_in9  (1'b0),                                          // (terminated)
		.reset_in10     (1'b0),                                          // (terminated)
		.reset_req_in10 (1'b0),                                          // (terminated)
		.reset_in11     (1'b0),                                          // (terminated)
		.reset_req_in11 (1'b0),                                          // (terminated)
		.reset_in12     (1'b0),                                          // (terminated)
		.reset_req_in12 (1'b0),                                          // (terminated)
		.reset_in13     (1'b0),                                          // (terminated)
		.reset_req_in13 (1'b0),                                          // (terminated)
		.reset_in14     (1'b0),                                          // (terminated)
		.reset_req_in14 (1'b0),                                          // (terminated)
		.reset_in15     (1'b0),                                          // (terminated)
		.reset_req_in15 (1'b0)                                           // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_002 (
		.reset_in0      (reset),                                        // reset_in0.reset
		.clk            (i_tse_pcs_0_pcs_receive_clock_connection_clk), //       clk.clk
		.reset_out      (rst_controller_002_reset_out_reset),           // reset_out.reset
		.reset_req      (),                                             // (terminated)
		.reset_req_in0  (1'b0),                                         // (terminated)
		.reset_in1      (1'b0),                                         // (terminated)
		.reset_req_in1  (1'b0),                                         // (terminated)
		.reset_in2      (1'b0),                                         // (terminated)
		.reset_req_in2  (1'b0),                                         // (terminated)
		.reset_in3      (1'b0),                                         // (terminated)
		.reset_req_in3  (1'b0),                                         // (terminated)
		.reset_in4      (1'b0),                                         // (terminated)
		.reset_req_in4  (1'b0),                                         // (terminated)
		.reset_in5      (1'b0),                                         // (terminated)
		.reset_req_in5  (1'b0),                                         // (terminated)
		.reset_in6      (1'b0),                                         // (terminated)
		.reset_req_in6  (1'b0),                                         // (terminated)
		.reset_in7      (1'b0),                                         // (terminated)
		.reset_req_in7  (1'b0),                                         // (terminated)
		.reset_in8      (1'b0),                                         // (terminated)
		.reset_req_in8  (1'b0),                                         // (terminated)
		.reset_in9      (1'b0),                                         // (terminated)
		.reset_req_in9  (1'b0),                                         // (terminated)
		.reset_in10     (1'b0),                                         // (terminated)
		.reset_req_in10 (1'b0),                                         // (terminated)
		.reset_in11     (1'b0),                                         // (terminated)
		.reset_req_in11 (1'b0),                                         // (terminated)
		.reset_in12     (1'b0),                                         // (terminated)
		.reset_req_in12 (1'b0),                                         // (terminated)
		.reset_in13     (1'b0),                                         // (terminated)
		.reset_req_in13 (1'b0),                                         // (terminated)
		.reset_in14     (1'b0),                                         // (terminated)
		.reset_req_in14 (1'b0),                                         // (terminated)
		.reset_in15     (1'b0),                                         // (terminated)
		.reset_req_in15 (1'b0)                                          // (terminated)
	);

endmodule
